#ifndef ZOMBIE_TYPE_HPP
#define ZOMBIE_TYPE_HPP

enum ZombieType : int {
    NORMAL_ZOMBIE,
    FLAG_ZOMBIE,
    CONEHEAD_ZOMBIE,
    POLE_VAULTING_ZOMBIE,
    BUCKETHEAD_ZOMBIE,
    NEWSPAPER_ZOMBIE,
    SCREEN_DOOR_ZOMBIE,
    FOOTBALL_ZOMBIE,
    DANCING_ZOMBIE,
    DANCER_ZOMBIE = DANCING_ZOMBIE,
    BACKUP_DANCER_ZOMBIE,
    DUCKY_TUBE_ZOMBIE,
    DUCKY_TUBE_CONEHEAD_ZOMBIE,
    DUCKY_TUBE_BUCKETHEAD_ZOMBIE,
    SNORKEL_ZOMBIE,
    ZOMBONI_ZOMBIE,
    BOBSLED_TEAM_ZOMBIE,
    DOLPHIN_RIDER_ZOMBIE,
    JACK_IN_THE_BOX_ZOMBIE,
    BALLOON_ZOMBIE,
    DIGGER_ZOMBIE,
    POGO_ZOMBIE,
    YETI_ZOMBIE,
    BUNGEE_ZOMBIE,
    LADDER_ZOMBIE,
    CATAPULT_ZOMBIE,
    GARGANTUAR_ZOMBIE,
    IMP_ZOMBIE,
    ZOMBOSS_ZOMBIE,
    ZOMBIE_CHARRED,
    ZOMBIE_COUNT
};

#endif
